name: Build PDF

on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.tex'
      - '**/*.bib'
      - '**/*.mk4'

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install texlive
      run: sudo apt install -y texlive-full
    - uses: actions/setup-java@v4
      with:
        distribution: 'graalvm' # See 'Supported distributions' for available options
        java-version: '21'
    - name: Compile arara
      run: ./compile.sh
    - name: Compile LaTeX document
      run: ./build.sh
    - uses: actions/upload-artifact@v4
      working-directory: build
      with:
        name: pdf
        path: |
          root.pdf
  build-pandoc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'graalvm' # See 'Supported distributions' for available options
        java-version: '21'
    - name: Compile arara
      run: ./compile.sh
    - name: Install texlive
      run: sudo apt install -y texlive-full
    - name: Compile LaTeX document
      run: ./build.sh
    - uses: docker://pandoc/core:3.5
      working-directory: build
      with:
        args: "-s root.tex -o root.md"
    - name: Run make4ht
      working-directory: build
      run: make4ht -s -u -x --format odt --loglevel info -e build.mk4 root.tex || exit 0
    - name: Install libreoffice
      working-directory: build
      run: sudo apt install -y libreoffice
    - name: Convert to docx
      working-directory: build
      run: soffice --convert-to docx root.odt
    - uses: actions/upload-artifact@v4
      working-directory: build
      with:
        name: pandoc
        path: |
          root.md
          root.odt
          root.docx
