name: Build PDF

on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.tex'
      - '**/*.bib'

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v3
      with:
        root_file: root.tex
        latexmk_use_xelatex: true
        latexmk_shell_escape: true
    - uses: actions/upload-artifact@v4
      with:
        name: document
        path: |
          root.pdf
