name: Build PDF

on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.tex'
      - '**/*.bib'

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v3
      with:
        root_file: root.tex
        latexmk_use_xelatex: true
        latexmk_shell_escape: true
    - uses: actions/upload-artifact@v4
      with:
        name: pdf
        path: |
          root.pdf
  build-pandoc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker://pandoc/core:3.5
      with:
        args: "-s root.tex -o root.md"
    - name: Run make4ht
      uses: docker://ghcr.io/michal-h21/make4ht-action:latest
      env:
        command: "make4ht -s -u -x --format odt root.tex"
    - name: Install libreoffice
      run: apt install -y libreoffice
    - name: Convert to docx
      run: soffice --convert-to docx root.odt
    - uses: actions/upload-artifact@v4
      with:
        name: pandoc
        path: |
          root.md
          root.odt
          root.docx
