name: Build PDF

on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.tex'
      - '**/*.bib'
      - '**/*.mk4'

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install texlive
      run: |
        cat /etc/apt/sources.list
        ls -la /etc/apt/sources.list.d
        sudo sed -i 's/azure\.//' /etc/apt/sources.list
        sudo apt-get update
        sudo apt install -y texlive-full
    - uses: actions/setup-java@v4
      with:
        distribution: 'graalvm' # See 'Supported distributions' for available options
        java-version: '21'
    - name: Compile arara
      run: ./compile.sh
    - name: Compile LaTeX document
      run: ./build.sh
    - uses: actions/upload-artifact@v4
      with:
        name: pdf
        path: |
          build/root.pdf
  build-pandoc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'graalvm' # See 'Supported distributions' for available options
        java-version: '21'
    - name: Compile arara
      run: ./compile.sh
    - name: Install texlive
      run: |
        sudo sed -i 's/azure\.//' /etc/apt/sources.list
        sudo apt-get update
        sudo apt install -y libreoffice pandoc texlive-full
    - name: Compile LaTeX document
      run: ./build.sh
    - name: Build markdown
      working-directory: build
      run: "pandoc -s root.tex -o root.md"
    - name: Run make4ht
      working-directory: build
      run: make4ht -s -u -l --format odt --loglevel info -e ../build.mk4 root.tex || exit 0
    - name: Convert to docx
      working-directory: build
      run: soffice --convert-to docx root.odt
    - uses: actions/upload-artifact@v4
      with:
        name: pandoc
        path: |
          build/root.md
          build/root.odt
          build/root.docx
